import Head from "next/head";
import styles from "@/styles/Home.module.css";
import PokeList from "@/components/PokeList/PokeList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Poke App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className={styles.header}>Pokédex</header>
        <PokeList />
      </main>
    </>
  );
}
